server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportaddict?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always
