insert into client (id,username,password, role,name, first_name, birth_date, email, phone) values (0,'root','$2a$12$jdTIR7bFOezUfttdnyfhsOh.deI8CvvhVnbxHVTqUJgu8fpzglNTG','ROLE_USER', 'test', 'test', '1993/01/10', 'test@test.com', 12032511);
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'adavidovits0', 'c4vMi85NC', 'ROLE_USER', 'Davidovits', 'Alfonse', 'adavidovits0@livejournal.com', '1997/07/10', '256-929-7908');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'revequot1', 'SKuXfehBUj', 'ROLE_USER', 'Evequot', 'Rupert', 'revequot1@yandex.ru', '1995/08/29', '943-919-3391');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'jguilbert2', 'FlKFnNyA', 'ROLE_USER', 'Guilbert', 'Jourdan', 'jguilbert2@adobe.com', '1998/01/13', '549-205-2013');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'awalcher3', 'd6Fvy1PGQl8', 'ROLE_USER', 'Walcher', 'Annis', 'awalcher3@pagesperso-orange.fr', '1999/10/31', '333-205-2918');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'bpole4', '3JZ8kezZqD', 'ROLE_USER', 'Pole', 'Bridie', 'bpole4@techcrunch.com', '1997/06/28', '675-167-8131');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'nangeli5', 'ELt9xqZl', 'ROLE_USER', 'Angeli', 'Nichol', 'nangeli5@hud.gov', '1996/08/29', '750-505-7357');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'pcasetti6', 'XRSdPfGcXhB', 'ROLE_USER', 'Casetti', 'Perle', 'pcasetti6@de.vu', '1993/06/01', '198-364-9428');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'bsill7', 'c8kGCtQ', 'ROLE_USER', 'Sill', 'Bertrando', 'bsill7@google.it', '2000/04/18', '441-659-4675');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'kchislett8', 'rIOTNQW3', 'ROLE_USER', 'Chislett', 'Kerwinn', 'kchislett8@cbslocal.com', '1997/08/07', '395-946-3714');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'mmackall9', '3UAap8', 'ROLE_USER', 'MacKall', 'Malva', 'mmackall9@nbcnews.com', '1998/06/13', '804-370-7029');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'echadbanda', 'BGhxC3OJr', 'ROLE_USER', 'Chadband', 'Evanne', 'echadbanda@google.co.uk', '1993/04/16', '301-260-7569');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'mduffilb', 'BlnEFZzkzy', 'ROLE_USER', 'Duffil', 'Merv', 'mduffilb@eventbrite.com', '1996/08/29', '425-692-1087');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'kbarnetc', 'RiMz5SS', 'ROLE_USER', 'Barnet', 'Katerina', 'kbarnetc@vk.com', '2000/03/10', '299-902-8031');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'mdeplacidod', 'P3lSiPRKvnm', 'ROLE_USER', 'Deplacido', 'Marissa', 'mdeplacidod@elegantthemes.com', '1996/05/10', '755-351-3009');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'ogreenheade', 'UmFs15', 'ROLE_USER', 'Greenhead', 'Ollie', 'ogreenheade@merriam-webster.com', '1993/08/26', '174-349-4888');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'gcawcuttf', '$2a$12$TzC4yPT8xv1MLLJtUJ.HrO7YZdokbG5QfJPzDRIiojGaXdxum4lpO', 'ROLE_USER', 'Cawcutt', 'Gail', 'gcawcuttf@shinystat.com', '1992/10/02', '260-372-4717');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'mjekyllg', '$2a$12$GGOwT02l/e6y0IWoFpPb5uFSba1UgLv8bzFzAQkgRUxpDu0tsN1nK', 'ROLE_USER', 'Jekyll', 'Marilin', 'mjekyllg@cbslocal.com', '1995/12/25', '760-236-0006');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'losanneh', '$2a$12$jFRrItj2WGZui/y8YiYpqOSLcgnN7RqozI.1hi7IsZXm4MzQWwO5G', 'ROLE_USER', 'Osanne', 'Lotty', 'losanneh@about.me', '1999/06/16', '354-655-2074');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'fsapautoni', '$2a$12$/FfeoBJ7fyw3B2EDoTPey.64tqCvlbpAKYxavMp6L8O/UMdVr32PG', 'ROLE_USER', 'Sapauton', 'Francene', 'fsapautoni@hud.gov', '1996/09/28', '856-744-7052');
insert into client (id, username, password, role, name, first_name, email, birth_date, phone) values (0, 'kbynethj', ' $2a$12$ICgYFWFuO7NuTYsEK8X5AeEM9WC2GhGHEMO6eLyVJGxp4Ma5neiHW', 'ROLE_USER', 'Byneth', 'Karmen', 'kbynethj@squarespace.com', '1996/06/15', '458-549-8843');
insert into client (id,username,password, role, name, first_name, birth_date, email, phone) values (0,'chris','$2a$12$/UpFSvMaaU42f6Lkf5idu.sJ2.Wq23x1Z4aPSGXdqfy61SaGW2rlu','ROLE_ADMIN', 'Havile', 'Renard', '1993/01/10', 'rhavilej@bigcartel.com', 12032511);

insert into owner (id, name, first_name, birth_date) values (0, 'Satchell', 'Alix', '1985/07/16');
insert into owner (id, name, first_name, birth_date) values (0, 'Deboick', 'Fabiano', '1984/01/13');
insert into owner (id, name, first_name, birth_date) values (0, 'Luten', 'Asher', '1985/01/02');
insert into owner (id, name, first_name, birth_date) values (0, 'Cloney', 'Westley', '1999/12/04');
insert into owner (id, name, first_name, birth_date) values (0, 'Leadbetter', 'Ivett', '1990/12/09');
insert into owner (id, name, first_name, birth_date) values (0, 'Babbe', 'Sig', '1994/11/11');
insert into owner (id, name, first_name, birth_date) values (0, 'Georgeon', 'Adan', '1999/03/26');
insert into owner (id, name, first_name, birth_date) values (0, 'Weeks', 'Concordia', '1987/01/20');
insert into owner (id, name, first_name, birth_date) values (0, 'Gethouse', 'Aurilia', '1983/11/04');
insert into owner (id, name, first_name, birth_date) values (0, 'Bruton', 'Mirabel', '1984/04/08');
insert into owner (id, name, first_name, birth_date) values (0, 'Rankmore', 'Vincenty', '1986/05/21');
insert into owner (id, name, first_name, birth_date) values (0, 'Welberry', 'Farleigh', '1983/02/25');
insert into owner (id, name, first_name, birth_date) values (0, 'Leinweber', 'Hervey', '1986/08/25');
insert into owner (id, name, first_name, birth_date) values (0, 'Joyce', 'Alvy', '1991/05/29');
insert into owner (id, name, first_name, birth_date) values (0, 'Konneke', 'Cletus', '1997/04/18');
insert into owner (id, name, first_name, birth_date) values (0, 'Haistwell', 'Hoyt', '1989/09/17');
insert into owner (id, name, first_name, birth_date) values (0, 'Bamber', 'Fernande', '1998/04/03');
insert into owner (id, name, first_name, birth_date) values (0, 'Headingham', 'Shelli', '1994/08/15');
insert into owner (id, name, first_name, birth_date) values (0, 'Collacombe', 'Rahel', '1999/04/18');
insert into owner (id, name, first_name, birth_date) values (0, 'Snowding', 'Harli', '1980/07/31');

insert into optiont (id,name) values (1,'piscine');
insert into optiont (id,name) values (2,'hamam');
insert into optiont (id,name) values (3,'sauna');
insert into optiont (id,name) values (4,'salle de boxe');
insert into optiont (id,name) values (5,'salle exercice collectif');
insert into optiont (id,name) values (6,'bar');

insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Mont-Laurier', 4532, 599,6);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Verkhnyaya Toyma', 4660, 593,7);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Karangbadar Kidul', 1807, 665,8);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Líbano', 3521, 575,10);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Malakwāl', 4491, 529,10);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Woro', 3156, 997,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Shimen', 1648, 857,15);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Qizhen', 1440, 717,15);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Aucayacu', 2634, 949,20);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Limonade', 1376, 619,19);
insert into fitness_hall (id, city, cp, area,owner_id) values (0, 'Krasnyye Chetai', 2914, 650,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Daguma', 2025, 526,2);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Giemdiem', 2195, 993,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Mātli', 3417, 806,6);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Fredrikstad', 1997, 945,1);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Sophia Antipolis', 3696, 681,1);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Krasni Okny', 2692, 850,16);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Guancheng', 4968, 671,14);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Barra Mansa', 2033, 919,13);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Paris 04', 4093, 991,17);

insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (1, 1, 12, 'ONE', '2021/09/11');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (2, 2, 6, 'FULL', '2022/03/29');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (3, 3, 12, 'FULL', '2021/08/12');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (5, 5, 12, 'FULL', '2022/01/19');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (6, 6, 6, 'ONE', '2022/02/19');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (7, 7, 3, 'ONE', '2021/09/20');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (8, 8, 12, 'ONE', '2022/03/19');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (9, 9, 12, 'FULL', '2022/01/20');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (10, 10, 6, 'ONE', '2021/10/03');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (11, 11, 6, 'FULL', '2021/09/05');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (12, 12, 12, 'ONE', '2021/05/26');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (13, 13, 12, 'ONE', '2021/12/24');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (14, 14, 12, 'ONE', '2021/07/21');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (15, 15, 12, 'ONE', '2022/01/11');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (16, 16, 6, 'ONE', '2021/09/16');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (17, 17, 3, 'FULL', '2021/11/26');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (18, 18, 12, 'ONE', '2021/08/24');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (19, 19, 6, 'ONE', '2022/01/03');
insert into subscription (client_id, fitness_id, contract_type, contract_access, expire_date) values (20, 20, 12, 'FULL', '2021/04/26');

insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (10, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (19, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 1);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (7, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (15, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (18, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (1, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (12, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (8, 4);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (14, 4);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (13, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (9, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (16, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (12, 4);