insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Thandi', 'Tobit', '1982/10/09', 'tthandi0@g.co', 10577724);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Prando', 'Wynnie', '1992/05/17', 'wprando1@naver.com', 12094760);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Buffin', 'Joellen', '1999/07/20', 'jbuffin2@admin.ch', 10715689);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Garlic', 'Hugh', '1989/08/29', 'hgarlic3@wikia.com', 11570821);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Kondratenko', 'Lou', '1992/01/20', 'lkondratenko4@unesco.org', 11189925);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Lamke', 'Bernard', '1982/09/22', 'blamke5@pinterest.com', 11898687);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Fever', 'Fabio', '1981/07/22', 'ffever6@tmall.com', 10365034);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Whotton', 'Honoria', '1985/12/06', 'hwhotton7@google.de', 11038115);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Dummett', 'Kimberli', '1985/06/16', 'kdummett8@guardian.co.uk', 12337145);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Ducker', 'Jasmine', '1983/10/24', 'jducker9@blinklist.com', 11830562);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Tunnow', 'Iseabal', '1999/07/27', 'itunnowa@ucsd.edu', 10270865);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Wilding', 'Erda', '1986/08/17', 'ewildingb@howstuffworks.com', 11938260);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Vasyukov', 'Rosanna', '1993/12/10', 'rvasyukovc@apple.com', 10774576);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Bault', 'Agnese', '1995/04/16', 'abaultd@china.com.cn', 12136408);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Hanssmann', 'Minette', '1999/05/04', 'mhanssmanne@mozilla.com', 10200294);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Duddan', 'Lion', '1987/02/13', 'lduddanf@washingtonpost.com', 11394842);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Smooth', 'Kalie', '1994/07/27', 'ksmoothg@blog.com', 11649874);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Godfroy', 'Justina', '1999/11/24', 'jgodfroyh@freewebs.com', 10046735);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Hodcroft', 'Isidore', '1989/04/07', 'ihodcrofti@scientificamerican.com', 11939915);
insert into client (id, name, first_name, birth_date, email, phone) values (0, 'Havile', 'Renard', '1993/01/10', 'rhavilej@bigcartel.com', 12032511);
insert into client (id,username,password, name, first_name, birth_date, email, phone) values (0,'chris','chris', 'Havile', 'Renard', '1993/01/10', 'rhavilej@bigcartel.com', 12032511);


insert into owner (id, name, first_name, birth_date) values (0, 'Satchell', 'Alix', '1985/07/16');
insert into owner (id, name, first_name, birth_date) values (0, 'Deboick', 'Fabiano', '1984/01/13');
insert into owner (id, name, first_name, birth_date) values (0, 'Luten', 'Asher', '1985/01/02');
insert into owner (id, name, first_name, birth_date) values (0, 'Cloney', 'Westley', '1999/12/04');
insert into owner (id, name, first_name, birth_date) values (0, 'Leadbetter', 'Ivett', '1990/12/09');
insert into owner (id, name, first_name, birth_date) values (0, 'Babbe', 'Sig', '1994/11/11');
insert into owner (id, name, first_name, birth_date) values (0, 'Georgeon', 'Adan', '1999/03/26');
insert into owner (id, name, first_name, birth_date) values (0, 'Weeks', 'Concordia', '1987/01/20');
insert into owner (id, name, first_name, birth_date) values (0, 'Gethouse', 'Aurilia', '1983/11/04');
insert into owner (id, name, first_name, birth_date) values (0, 'Bruton', 'Mirabel', '1984/04/08');
insert into owner (id, name, first_name, birth_date) values (0, 'Rankmore', 'Vincenty', '1986/05/21');
insert into owner (id, name, first_name, birth_date) values (0, 'Welberry', 'Farleigh', '1983/02/25');
insert into owner (id, name, first_name, birth_date) values (0, 'Leinweber', 'Hervey', '1986/08/25');
insert into owner (id, name, first_name, birth_date) values (0, 'Joyce', 'Alvy', '1991/05/29');
insert into owner (id, name, first_name, birth_date) values (0, 'Konneke', 'Cletus', '1997/04/18');
insert into owner (id, name, first_name, birth_date) values (0, 'Haistwell', 'Hoyt', '1989/09/17');
insert into owner (id, name, first_name, birth_date) values (0, 'Bamber', 'Fernande', '1998/04/03');
insert into owner (id, name, first_name, birth_date) values (0, 'Headingham', 'Shelli', '1994/08/15');
insert into owner (id, name, first_name, birth_date) values (0, 'Collacombe', 'Rahel', '1999/04/18');
insert into owner (id, name, first_name, birth_date) values (0, 'Snowding', 'Harli', '1980/07/31');

insert into optiont (id,name) values (0,'piscine');
insert into optiont (id,name) values (1,'hamam');
insert into optiont (id,name) values (2,'sauna');
insert into optiont (id,name) values (3,'salle de boxe');
insert into optiont (id,name) values (4,'salle exercice collectif');
insert into optiont (id,name) values (5,'bar');

insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Mont-Laurier', 4532, 599,6);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Verkhnyaya Toyma', 4660, 593,7);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Karangbadar Kidul', 1807, 665,8);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Líbano', 3521, 575,10);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Malakwāl', 4491, 529,10);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Woro', 3156, 997,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Shimen', 1648, 857,15);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Qizhen', 1440, 717,15);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Aucayacu', 2634, 949,20);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Limonade', 1376, 619,19);
insert into fitness_hall (id, city, cp, area,owner_id) values (0, 'Krasnyye Chetai', 2914, 650,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Daguma', 2025, 526,2);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Giemdiem', 2195, 993,3);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Mātli', 3417, 806,6);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Fredrikstad', 1997, 945,1);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Sophia Antipolis', 3696, 681,1);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Krasni Okny', 2692, 850,16);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Guancheng', 4968, 671,14);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Barra Mansa', 2033, 919,13);
insert into fitness_hall (id, city, cp, area, owner_id) values (0, 'Paris 04', 4093, 991,17);

insert into subscription (client_id, fitness_id, contract_type, expire_date) values (1, 1, 6, '2023/06/26');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (2, 2, 6, '2022/12/19');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (3, 3, 3, '2023/05/13');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (4, 4, 12, '2023/02/25');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (5, 5, 6, '2022/06/12');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (6, 6, 12, '2023/03/09');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (7, 7, 12, '2022/06/29');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (8, 8, 12, '2023/05/26');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (9, 9, 6, '2023/05/23');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (10, 10, 3, '2022/12/09');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (11, 11, 3, '2022/06/23');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (12, 12, 3, '2023/05/28');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (13, 13, 6, '2023/07/08');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (14, 14, 12, '2022/05/17');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (15, 15, 6, '2023/09/12');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (16, 16, 6, '2023/02/18');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (17, 17, 6, '2022/09/27');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (18, 18, 3, '2023/04/13');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (19, 19, 3, '2023/04/28');
insert into subscription (client_id, fitness_id, contract_type, expire_date) values (20, 20, 6, '2023/06/17');

insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (10, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (19, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (20, 1);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (7, 5);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (15, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (18, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (1, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (12, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (8, 4);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (14, 4);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (13, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (9, 6);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (16, 2);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (6, 3);
insert into fitness_hall_option_list (fitness_hall_list_id, option_list_id) values (12, 4);